export enum Operator {
  Airlink = "Airlink",
  Connect = "Connect",
  Express = "Express",
  Waterline = "Waterline",
  Metro = "Metro",
  NationalRail = "National Rail",
  TransportForStepford = "Transport for Stepford",
}

export enum SignalZone {
  A = "A",
  B = "B",
  C = "C",
  D = "D",
  E = "E",
  F = "F",
  G = "G",
  H = "H",
  J = "J",
}

export type RouteInfo = {
  operator: Operator;
  inboundDestination: string;
  inboundDepots?: string[];
  outboundDestination?: string;
  outboundDepots?: string[];
  altName?: string;
};

export const routes: Record<string, RouteInfo> = {
  R001: {
    operator: Operator.Connect,
    inboundDestination: "Stepford Central",
    inboundDepots: [
      "Farleigh Depot (Road 11)",
      "Benton Depot",
      "Stepford Depot",
    ],
    outboundDestination: "Airport Central",
    outboundDepots: ["Coxly Station Siding", "Coxly Bypass Siding"],
  },
  R002: {
    operator: Operator.Metro,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Benton Depot", "Stepford Depot"],
    outboundDestination: "Port Benton",
    outboundDepots: ["Coxly Station Siding", "Coxly Bypass Siding"],
  },
  R003: {
    operator: Operator.Connect,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Benton Depot", "Stepford Depot"],
    outboundDestination: "Leighton City",
    outboundDepots: [
      "Coxly Station Siding",
      "Coxly Bypass Siding",
      "Hampton Hargate Siding",
      "Leighton Depot",
    ],
  },
  R004: {
    operator: Operator.Connect,
    inboundDestination: "St Helens Bridge",
    inboundDepots: ["Faymere Green NB Depot", "Benton Depot"],
    outboundDestination: "Edgemead",
    outboundDepots: [
      "Coxly Station Siding",
      "Coxly Bypass Siding",
      "Hampton Hargate Siding",
      "Leighton Depot",
    ],
  },
  R005: {
    operator: Operator.Connect,
    inboundDestination: "Stepford Victoria",
    inboundDepots: [
      "Farleigh Depot (Road 11)",
      "Benton Depot",
      "Stepford Depot",
      "Beechley Sidings",
    ],
    outboundDestination: "Airport Central",
    outboundDepots: [
      "Beechley Sidings",
      "Coxly Station Siding",
      "Coxly Bypass Siding",
    ],
  },
  R006: {
    operator: Operator.Metro,
    inboundDestination: "Stepford Victoria",
    inboundDepots: ["Benton Depot", "Stepford Depot", "Beechley Sidings"],
    outboundDestination: "Port Benton",
    outboundDepots: [
      "Beechley Sidings",
      "Coxly Station Siding",
      "Coxly Bypass Siding",
    ],
  },
  R007: {
    operator: Operator.Connect,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Berrily Depot (WB)", "Stepford Depot"],
    outboundDestination: "Morganstown",
    outboundDepots: ["Berrily Depot (EB)"],
  },
  R008: {
    operator: Operator.Metro,
    inboundDestination: "Stepford Victoria",
    inboundDepots: ["Berrily Depot (WB)", "Stepford Depot", "Beechley Sidings"],
    outboundDestination: "Berrily",
    outboundDepots: ["Beechley Sidings"],
  },
  R009: {
    operator: Operator.Metro,
    inboundDestination: "Stepford Victoria",
    inboundDepots: [
      "Faymere Green NB Depot",
      "Benton Depot",
      "Stepford Depot",
      "Beechley Sidings",
    ],
    outboundDestination: "Edgemead",
    outboundDepots: [
      "Beechley Sidings",
      "Coxly Station Siding",
      "Coxly Bypass Siding",
      "Hampton Hargate Siding",
      "Leighton Depot",
    ],
  },
  R010: {
    operator: Operator.Waterline,
    inboundDestination: "Newry",
    inboundDepots: ["Faraday Road Depot", "Newry Siding"],
    outboundDestination: "Greenslade",
    outboundDepots: ["Benton Siding", "Whitney Green Depot"],
  },
  R011: {
    operator: Operator.Waterline,
    inboundDestination: "Newry",
    inboundDepots: ["Faraday Road Depot", "Newry Siding"],
    outboundDestination: "Connolly",
    outboundDepots: ["Benton Siding"],
  },
  R012: {
    operator: Operator.Waterline,
    inboundDestination: "Newry Harbour",
    inboundDepots: ["Faraday Road Depot", "Newry Siding"],
    outboundDestination: "Connolly",
    outboundDepots: ["Benton Siding"],
  },
  R013: {
    operator: Operator.Waterline,
    inboundDestination: "Benton",
    outboundDestination: "Greenslade",
    outboundDepots: ["Benton Siding", "Whitney Green Depot"],
  },
  R014: {
    operator: Operator.Waterline,
    inboundDestination: "Newry",
    inboundDepots: [
      "Esterfield Mainline Depot",
      "Faraday Road Depot",
      "Newry Siding",
    ],
    outboundDestination: "Esterfield",
    outboundDepots: [
      "Benton Siding",
      "Farleigh Depot (Road 2)",
      "Esterfield Station Depot",
    ],
  },
  R015: {
    operator: Operator.Waterline,
    inboundDestination: "Benton",
    inboundDepots: ["Morganstown Siding"],
    outboundDestination: "Morganstown",
    outboundDepots: ["Benton Siding"],
    altName: "Morganstown Shuttle",
  },
  R016: {
    operator: Operator.Waterline,
    inboundDestination: "Benton",
    inboundDepots: ["Esterfield Mainline Depot"],
    outboundDestination: "Esterfield",
    outboundDepots: [
      "Benton Siding",
      "Farleigh Depot (Road 2)",
      "Esterfield Station Depot",
    ],
  },
  R017: {
    operator: Operator.Waterline,
    inboundDestination: "Newry",
    inboundDepots: ["Faraday Road Depot", "Newry Siding"],
    outboundDestination: "Terminal 2",
    outboundDepots: ["Benton Siding", "Farleigh Depot (Road 17)"],
  },
  R018: {
    operator: Operator.Waterline,
    inboundDestination: "Newry Harbour",
    inboundDepots: ["Faraday Road Depot", "Newry Siding"],
    outboundDestination: "Farleigh",
    outboundDepots: ["Benton Siding", "Farleigh Depot (Road 2)"],
  },
  R019: {
    operator: Operator.Waterline,
    inboundDestination: "Benton",
    outboundDestination: "Connolly",
    outboundDepots: ["Benton Siding"],
  },
  R020: {
    operator: Operator.Connect,
    inboundDestination: "Stepford Central",
    inboundDepots: [
      "Whitefield Siding",
      "Woodhead Lane SB Depot",
      "Stepford Depot",
    ],
    outboundDestination: "Whitefield",
    outboundDepots: ["Woodhead Lane NB Depot"],
  },
  R021: {
    operator: Operator.Metro,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Woodhead Lane SB Depot", "Stepford Depot"],
    outboundDestination: "Stepford United Football Club",
  },
  R022: {
    operator: Operator.Connect,
    inboundDestination: "Beechley",
    inboundDepots: [
      "Whitefield Siding",
      "Woodhead Lane SB Depot",
      "Stepford Depot",
    ],
    outboundDestination: "Whitefield",
    outboundDepots: ["Beechley Sidings", "Woodhead Lane NB Depot"],
  },
  R023: {
    operator: Operator.Metro,
    inboundDestination: "Stepford Victoria",
    inboundDepots: [
      "Woodhead Lane SB Depot",
      "Stepford Depot",
      "Beechley Sidings",
    ],
    outboundDestination: "Stepford United Football Club",
    outboundDepots: ["Beechley Sidings"],
  },
  R024: {
    operator: Operator.Connect,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Faymere Green NB Depot", "Benton Depot", "Stepford Depot"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: [
      "Coxly Station Siding",
      "Coxly Bypass Siding",
      "Hampton Hargate Siding",
      "Leighton Depot",
      "Faymere Green SB Depot",
      "Northshore Depot",
    ],
  },
  R025: {
    operator: Operator.Connect,
    inboundDestination: "St Helens Bridge",
    inboundDepots: ["Faymere Green NB Depot", "Benton Depot"],
    outboundDestination: "Westwyern",
    outboundDepots: [
      "Coxly Station Siding",
      "Coxly Bypass Siding",
      "Hampton Hargate Siding",
      "Leighton Depot",
      "Faymere Green SB Depot",
    ],
  },
  R026: {
    operator: Operator.Connect,
    inboundDestination: "Stepford Victoria",
    inboundDepots: [
      "Faymere Green NB Depot",
      "Benton Depot",
      "Stepford Depot",
      "Beechley Sidings",
    ],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: [
      "Beechley Sidings",
      "Coxly Station Siding",
      "Coxly Bypass Siding",
      "Hampton Hargate Siding",
      "Leighton Depot",
      "Faymere Green SB Depot",
      "Northshore Depot",
    ],
  },
  R027: {
    operator: Operator.Metro,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Berrily Depot (WB)", "Stepford Depot"],
    outboundDestination: "Berrily",
  },
  R028: {
    operator: Operator.Metro,
    inboundDestination: "Stepford Victoria",
    inboundDepots: ["Willowfield Depot", "Beechley Sidings"],
    outboundDestination: "Willowfield",
    outboundDepots: ["Willowfield Depot"],
  },
  R029: {
    operator: Operator.Metro,
    inboundDestination: "Stepford Victoria",
    inboundDepots: ["Beechley Sidings"],
    outboundDestination: "Beechley",
  },
  R030: {
    operator: Operator.Metro,
    inboundDestination: "Willowfield",
    inboundDepots: [
      "Berrily Depot (WB)",
      "Stepford Depot",
      "Willowfield Depot",
    ],
    outboundDestination: "Berrily",
    outboundDepots: ["Willowfield Depot", "Beechley Sidings"],
  },
  R031: {
    operator: Operator.Metro,
    inboundDestination: "Willowfield",
    inboundDepots: ["Woodhead Lane SB Depot"],
    outboundDestination: "Stepford United Football Club",
    outboundDepots: ["Willowfield Depot", "Beechley Sidings"],
  },
  R032: {
    operator: Operator.Connect,
    inboundDestination: "Willowfield",
    inboundDepots: ["Benton Depot", "Stepford Depot", "Willowfield Depot"],
    outboundDestination: "Port Benton",
    outboundDepots: [
      "Willowfield Depot",
      "Beechley Sidings",
      "Coxly Station Siding",
      "Coxly Bypass Siding",
    ],
  },
  R033: {
    operator: Operator.Connect,
    inboundDestination: "Beechley",
    inboundDepots: [
      "Farleigh Depot (Road 11)",
      "Benton Depot",
      "Stepford Depot",
    ],
    outboundDestination: "Airport Central",
    outboundDepots: [
      "Beechley Sidings",
      "Coxly Station Siding",
      "Coxly Bypass Siding",
    ],
  },
  R034: {
    operator: Operator.Metro,
    inboundDestination: "Beechley",
    inboundDepots: ["Berrily Depot (WB)", "Stepford Depot"],
    outboundDestination: "Morganstown",
    outboundDepots: ["Beechley Sidings", "Berrily Depot (EB)"],
  },
  R035: {
    operator: Operator.Connect,
    inboundDestination: "Willowfield",
    inboundDepots: [
      "Faymere Green NB Depot",
      "Benton Depot",
      "Stepford Depot",
      "Willowfield Depot",
    ],
    outboundDestination: "Westwyvern",
    outboundDepots: [
      "Willowfield Depot",
      "Beechley Sidings",
      "Coxly Station Siding",
      "Coxly Bypass Siding",
      "Hampton Hargate Siding",
      "Leighton Depot",
      "Faymere Green SB Depot",
    ],
  },
  R036: {
    operator: Operator.Connect,
    inboundDestination: "Willowfield",
    inboundDepots: [
      "Faymere Green NB Depot",
      "Benton Depot",
      "Stepford Depot",
      "Willowfield Depot",
    ],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: [
      "Willowfield Depot",
      "Beechley Sidings",
      "Coxly Station Siding",
      "Coxly Bypass Siding",
      "Hampton Hargate Siding",
      "Leighton Depot",
      "Faymere Green SB Depot",
      "Northshore Depot",
    ],
  },
  R037: {
    operator: Operator.Connect,
    inboundDestination: "Leighton City",
    inboundDepots: ["Faymere Green NB Depot"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: ["Faymere Green SB Depot", "Northshore Depot"],
  },
  R038: {
    operator: Operator.Connect,
    inboundDestination: "Leighton City",
    inboundDepots: ["Faymere Green NB Depot"],
    outboundDestination: "Westwyvern",
    outboundDepots: ["Faymere Green SB Depot"],
  },
  R039: {
    operator: Operator.Connect,
    inboundDestination: "Benton",
    outboundDestination: "Leighton City",
    outboundDepots: [
      "Coxly Bypass Siding",
      "Hampton Hargate Siding",
      "Leighton Depot",
    ],
  },
  R040: {
    operator: Operator.Connect,
    inboundDestination: "Edgemead",
    inboundDepots: ["Faymere Green NB Depot"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: ["Faymere Green SB Depot", "Northshore Depot"],
  },
  R041: {
    operator: Operator.Connect,
    inboundDestination: "Leighton West",
    inboundDepots: ["Faymere Green NB Depot"],
    outboundDestination: "Edgemead",
  },
  R042: {
    operator: Operator.Connect,
    inboundDestination: "Leighton West",
    inboundDepots: ["Faymere Green NB Depot"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: ["Faymere Green SB Depot", "Northshore Depot"],
  },
  R043: {
    operator: Operator.Connect,
    inboundDestination: "Leighton West",
    inboundDepots: ["Leighton Depot"],
    outboundDestination: "Leighton City",
  },
  R044: {
    operator: Operator.Connect,
    inboundDestination: "Benton",
    outboundDestination: "Leighton West",
    outboundDepots: [
      "Coxly Bypass Siding",
      "Hampton Hargate Siding",
      "Leighton Depot",
    ],
  },
  R045: {
    operator: Operator.Connect,
    inboundDestination: "Stepford Victoria",
    inboundDepots: ["Benton Depot", "Stepford Depot", "Beechley Sidings"],
    outboundDestination: "Leighton City",
    outboundDepots: [
      "Beechley Sidings",
      "Coxly Station Siding",
      "Coxly Bypass Siding",
      "Hampton Hargate Siding",
      "Leighton Depot",
    ],
  },
  R046: {
    operator: Operator.Connect,
    inboundDestination: "Stepford Victoria",
    inboundDepots: [
      "Farleigh Depot (Road 11)",
      "Benton Depot",
      "Stepford Depot",
      "Beechley Sidings",
    ],
    outboundDestination: "Terminal 2",
    outboundDepots: [
      "Beechley Sidings",
      "Coxly Station Siding",
      "Coxly Bypass Siding",
      "Farleigh Depot (Road 17)",
    ],
  },
  R047: {
    operator: Operator.Metro,
    inboundDestination: "St Helens Bridge",
    inboundDepots: ["Benton Depot"],
    outboundDestination: "Port Benton",
    outboundDepots: ["Coxly Station Siding", "Coxly Bypass Siding"],
  },
  R048: {
    operator: Operator.Connect,
    inboundDestination: "St Helens Bridge",
    inboundDepots: ["	Farleigh Depot (Road 11)", "Benton Depot"],
    outboundDestination: "Terminal 2",
    outboundDepots: [
      "Coxly Station Siding",
      "Coxly Bypass Siding",
      "Farleigh Depot (Road 17)",
    ],
  },
  R049: {
    operator: Operator.Connect,
    inboundDestination: "Rayleigh Bay",
    inboundDepots: ["Faymere Green NB Depot"],
    outboundDestination: "Edgemead",
  },
  R050: {
    operator: Operator.Connect,
    inboundDestination: "Rayleigh Bay",
    inboundDepots: ["Faymere Green NB Depot"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: ["Faymere Green SB Depot", "Northshore Depot"],
  },
  R051: {
    operator: Operator.Airlink,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Farleigh Depot (Road 11)", "Stepford Depot"],
    outboundDestination: "Airport Central",
    outboundDepots: ["Airport Parkway Siding"],
  },
  R052: {
    operator: Operator.Airlink,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Farleigh Depot (Road 11)", "Stepford Depot"],
    outboundDestination: "Terminal 2",
    outboundDepots: ["Airport Parkway Siding", "Airport Parkway Siding"],
  },
  R053: {
    operator: Operator.Airlink,
    inboundDestination: "Stepford Central",
    inboundDepots: [
      "Farleigh Depot (Road 11)",
      "Airport Parkway Depot",
      "Stepford Depot",
    ],
    outboundDestination: "Terminal 2",
    outboundDepots: ["Airport Parkway Siding", "Farleigh Depot (Road 17)"],
  },
  R054: {
    operator: Operator.Airlink,
    inboundDestination: "Stepford Central",
    inboundDepots: [
      "Farleigh Depot (Road 11)",
      "Airport Parkway Depot",
      "Stepford Depot",
    ],
    outboundDestination: "Airport Central",
    outboundDepots: ["Airport Parkway Siding"],
  },
  R055: {
    operator: Operator.Airlink,
    inboundDestination: "Stepford Central",
    inboundDepots: [
      "Farleigh Depot (Road 11)",
      "Airport Parkway Depot",
      "Stepford Depot",
    ],
    outboundDestination: "Terminal 3",
    outboundDepots: ["Airport Parkway Siding", "Farleigh Depot (Road 17)"],
  },
  R056: {
    operator: Operator.Airlink,
    inboundDestination: "Airport Central",
    inboundDepots: ["Airport Parkway Siding"],
    outboundDestination: "Leighton Stepford Road",
    outboundDepots: ["Farleigh Depot (Road 11)", "Leighton Depot"],
  },
  R057: {
    operator: Operator.Airlink,
    inboundDestination: "Terminal 3",
    inboundDepots: ["Farleigh Depot (Road 17)"],
    outboundDestination: "Leighton Stepford Road",
    outboundDepots: [
      "Farleigh Depot (Road 11)",
      "Airport Parkway Depot",
      "Leighton Depot",
    ],
  },
  R058: {
    operator: Operator.Airlink,
    inboundDestination: "Stepford Central",
    inboundDepots: [
      "Farleigh Depot (Road 17)",
      "Farleigh Depot (Road 11)",
      "Stepford Depot",
    ],
    outboundDestination: "Terminal 3",
    outboundDepots: ["Airport Parkway Siding"],
  },
  R059: {
    operator: Operator.Airlink,
    inboundDestination: "Stepford Central",
    inboundDepots: [
      "Farleigh Depot (Road 11)",
      "Airport Parkway Depot",
      "Stepford Depot",
    ],
    outboundDestination: "Terminal 2",
    outboundDepots: ["Airport Parkway Siding", "Farleigh Depot (Road 17)"],
  },
  R060: {
    operator: Operator.Airlink,
    inboundDestination: "Airport Parkway",
    inboundDepots: ["Farleigh Depot (Road 11)"],
    outboundDestination: "Terminal 2",
    outboundDepots: ["Airport Parkway Siding", "Farleigh Depot (Road 17)"],
    altName: "Terminals Shuttle",
  },
  R061: {
    operator: Operator.Airlink,
    inboundDestination: "Airport Central",
    inboundDepots: ["Faymere Green NB Depot", "Airport Parkway Siding"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: [
      "Farleigh Depot (Road 11)",
      "Leighton Depot",
      "Faymere Green SB Depot",
      "Northshore Depot",
    ],
  },
  R062: {
    operator: Operator.Airlink,
    inboundDestination: "Terminal 3",
    inboundDepots: ["Faymere Green NB Depot", "Airport Parkway Siding"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: [
      "Farleigh Depot (Road 17)",
      "Farleigh Depot (Road 11)",
      "Leighton Depot",
      "Faymere Green SB Depot",
      "Northshore Depot",
    ],
  },
  R075: {
    operator: Operator.Express,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Benton Depot", "Stepford Depot"],
    outboundDestination: "Benton",
    outboundDepots: ["Coxly Bypass Siding"],
    altName: "Benton Express (fast)",
  },
  R076: {
    operator: Operator.Express,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Benton Depot", "Stepford Depot"],
    outboundDestination: "Leighton City",
    outboundDepots: ["Coxly Bypass Siding", "Leighton Depot"],
    altName: "Leighton Express",
  },
  R077: {
    operator: Operator.Express,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Faymere Green NB Depot", "Benton Depot", "Stepford Depot"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: [
      "Coxly Bypass Siding",
      "Leighton Depot",
      "Faymere Green SB Depot",
      "Northshore Depot",
    ],
    altName: "Llyn via Benton",
  },
  R078: {
    operator: Operator.Express,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Faymere Green NB Depot", "Benton Depot", "Stepford Depot"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: [
      "Coxly Bypass Siding",
      "Leighton Depot",
      "Faymere Green SB Depot",
      "Northshore Depot",
    ],
    altName: "Llyn via Benton (fast)",
  },
  R079: {
    operator: Operator.Express,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Benton Depot", "Stepford Depot"],
    outboundDestination: "Benton",
    outboundDepots: ["Coxly Bypass Siding"],
    altName: "Benton Express",
  },
  R080: {
    operator: Operator.Express,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Faymere Green NB Depot", "Stepford Depot"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: [
      "Leighton Depot",
      "Faymere Green SB Depot",
      "Northshore Depot",
    ],
    altName: "Llyn via Morganstown (fast)",
  },
  R081: {
    operator: Operator.Express,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Faymere Green NB Depot", "Stepford Depot"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: ["Leighton Depot", "Northshore Depot"],
    altName: "Llyn (super fast)",
  },
  R082: {
    operator: Operator.Express,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Faymere Green NB Depot", "Stepford Depot"],
    outboundDestination: "Westwyvern",
    outboundDepots: ["Leighton Depot", "Faymere Green SB Depot"],
    altName: "Westwyvern Express",
  },
  R083: {
    operator: Operator.Express,
    inboundDestination: "Newry",
    inboundDepots: ["Faymere Green NB Depot", "Newry Siding"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: [
      "Leighton Depot",
      "Faymere Green SB Depot",
      "Northshore Depot",
    ],
    altName: "Newry to Llyn",
  },
  R084: {
    operator: Operator.Express,
    inboundDestination: "Newry Harbour",
    inboundDepots: ["Faymere Green NB Depot", "Newry Siding"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: [
      "Leighton Depot",
      "Faymere Green SB Depot",
      "Northshore Depot",
    ],
    altName: "Newry Harbour to Llyn",
  },
  R085: {
    operator: Operator.Express,
    inboundDestination: "Benton",
    inboundDepots: ["Faymere Green NB Depot"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: [
      "Leighton Depot",
      "Faymere Green SB Depot",
      "Northshore Depot",
    ],
    altName: "Benton to Llyn",
  },
  R086: {
    operator: Operator.Express,
    inboundDestination: "Newry",
    inboundDepots: ["Faraday Road Depot", "Newry Siding"],
    outboundDestination: "Leighton City",
    outboundDepots: ["Leighton Depot"],
    altName: "Newry to Leighton City",
  },
  R087: {
    operator: Operator.Express,
    inboundDestination: "Llyn-by-the-Sea",
    inboundDepots: ["Faymere Green SB Depot", "Northshore Depot"],
    outboundDestination: "Rayleigh Bay",
    outboundDepots: ["Faymere Green NB Depot"],
    altName: "Rayleigh Bay Express",
  },
  R088: {
    operator: Operator.Express,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Faymere Green NB Depot", "Benton Depot", "Stepford Depot"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: [
      "Coxly Bypass Siding",
      "Leighton Depot",
      "Faymere Green SB Depot",
      "Northshore Depot",
    ],
    altName: "Llyn via Benton (Westercoast Express)",
  },
  R100: {
    operator: Operator.Connect,
    inboundDestination: "Rayleigh Bay",
    inboundDepots: ["Leighton Depot"],
    outboundDestination: "Leighton West",
    outboundDepots: ["Faymere Green NB Depot"],
  },
  R101: {
    operator: Operator.Connect,
    inboundDestination: "Rayleigh Bay",
    inboundDepots: ["Leighton Depot"],
    outboundDestination: "Leighton City",
  },
  R102: {
    operator: Operator.Connect,
    inboundDestination: "Rayleigh Bay",
    inboundDepots: ["Faymere Green NB Depot"],
    outboundDestination: "Westwyvern",
    outboundDepots: ["Faymere Green SB Depot"],
  },
  R103: {
    operator: Operator.Connect,
    inboundDestination: "Willowfield",
    inboundDepots: [
      "Whitefield Siding",
      "Woodhead Lane SB Depot",
      "Stepford Depot",
      "Willowfield Depot",
    ],
    outboundDestination: "Whitefield",
    outboundDepots: [
      "Willowfield Depot",
      "Beechley Sidings",
      "Woodhead Lane NB Depot",
    ],
  },
  R120: {
    operator: Operator.Waterline,
    inboundDestination: "Newry Harbour",
    inboundDepots: ["Morganstown Siding", "Faraday Road Depot", "Newry Siding"],
    outboundDestination: "Morganstown",
    outboundDepots: ["Benton Siding"],
  },
  R130: {
    operator: Operator.Metro,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Berrily Depot (WB)", "Stepford Depot"],
    outboundDestination: "Morganstown",
    outboundDepots: ["Berrily Depot (EB)"],
  },
  R131: {
    operator: Operator.Metro,
    inboundDestination: "St Helens Bridge",
    inboundDepots: ["Berrily Depot (WB)"],
    outboundDestination: "Morganstown",
    outboundDepots: ["Berrily Depot (EB)"],
  },
  R132: {
    operator: Operator.Metro,
    inboundDestination: "Barton",
    outboundDestination: "Stepford Central",
    outboundDepots: ["Berrily Depot (WB)", "Stepford Depot"],
    altName: "Stepford Central <> Barton (Clockwise)",
  },
  R133: {
    operator: Operator.Metro,
    inboundDestination: "Barton",
    inboundDepots: ["Willowfield Depot", "Beechley Sidings"],
    outboundDestination: "Willowfield",
    outboundDepots: [
      "Willowfield Depot",
      "Stepford Depot",
      "Berrily Depot (WB)",
    ],
    altName: "Willowfield <> Barton (Clockwise)",
  },
  R134: {
    operator: Operator.Metro,
    inboundDestination: "Barton",
    outboundDestination: "St Helens Bridge",
    outboundDepots: ["Berrily Depot (WB)"],
    altName: "St Helens Bridge <> Barton (Clockwise)",
  },
  R135: {
    operator: Operator.Metro,
    inboundDestination: "Barton",
    inboundDepots: ["Beechley Sidings"],
    outboundDestination: "Beechley",
    outboundDepots: ["Stepford Depot"],
    altName: "Beechley <> Barton (Anti-clockwise)",
  },
  R136: {
    operator: Operator.Metro,
    inboundDestination: "Barton",
    inboundDepots: ["Beechley Sidings"],
    outboundDestination: "Stepford Victoria",
    outboundDepots: ["Stepford Depot", "Beechley Sidings"],
    altName: "Stepford Victoria <> Barton (Anti-clockwise)",
  },
  R137: {
    operator: Operator.Metro,
    inboundDestination: "Stepford Victoria",
    inboundDepots: [
      "Morganstown Siding",
      "Benton Depot",
      "Stepford Depot",
      "Beechley Sidings",
    ],
    outboundDestination: "Morganstown",
    outboundDepots: [
      "Beechley Sidings",
      "Coxly Station Siding",
      "Coxly Bypass Siding",
    ],
    altName: "Stepford Victoria <> M'Town via Benton",
  },
};

export type StationInfo = {
  name: string;
  operators: Operator[];
  managers: Operator[];
  signalZone: SignalZone[];
  platforms: (string | number)[];
  dsGroups?: (string | number)[][];
};

export const stations: Record<string, StationInfo> = {
  AGP: {
    name: "Angel Pass",
    operators: [Operator.Connect, Operator.Metro],
    managers: [Operator.Metro, Operator.TransportForStepford],
    signalZone: [SignalZone.B],
    platforms: [1, 2, 3],
    dsGroups: [[1, 2, 3]],
  },
  ALB: {
    name: "Aslockby",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signalZone: [SignalZone.H],
    platforms: [1, 2],
  },
  APK: {
    name: "Ashlan Park",
    operators: [Operator.Waterline],
    managers: [Operator.Waterline],
    signalZone: [SignalZone.F],
    platforms: [1, 2],
  },
  BNB: {
    name: "Benton Bridge",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signalZone: [SignalZone.C],
    platforms: [1, 2, 3, 4],
    dsGroups: [[1, 2, 3, 4]],
  },
  BAR: {
    name: "Barton",
    operators: [Operator.Metro],
    managers: [Operator.Metro, Operator.TransportForStepford],
    signalZone: [SignalZone.B],
    platforms: [1, 2],
    dsGroups: [[1, 2]],
  },
  BCY: {
    name: "Beechley",
    operators: [Operator.Connect, Operator.Metro],
    managers: [Operator.Metro, Operator.TransportForStepford],
    signalZone: [SignalZone.A],
    platforms: [1, 2, 3, 4],
    dsGroups: [[1, 2, 3, 4]],
  },
  BEN: {
    name: "Benton",
    operators: [
      Operator.Connect,
      Operator.Metro,
      Operator.Waterline,
      Operator.Express,
    ],
    managers: [Operator.NationalRail],
    signalZone: [SignalZone.F],
    platforms: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
    dsGroups: [
      [1, 2, 3],
      [4, 5, 6, 7],
      [8, 9, 10, 11, 12, 13],
    ],
  },
  BOD: {
    name: "Bodin",
    operators: [Operator.Connect, Operator.Metro],
    managers: [Operator.Metro, Operator.TransportForStepford],
    signalZone: [SignalZone.B],
    platforms: [1, 2, 3],
    dsGroups: [[1, 2, 3]],
  },
  BPK: {
    name: "Beaulieu Park",
    operators: [Operator.Metro],
    managers: [Operator.Metro, Operator.TransportForStepford],
    signalZone: [SignalZone.B],
    platforms: [1, 2],
    dsGroups: [[1, 2]],
  },
  BRY: {
    name: "Berrily",
    operators: [Operator.Connect, Operator.Metro, Operator.Airlink],
    managers: [Operator.Metro, Operator.TransportForStepford],
    signalZone: [SignalZone.B],
    platforms: [1, 2, 3, 4],
    dsGroups: [[1, 2, 3, 4]],
  },
  CHP: {
    name: "City Hospital",
    operators: [Operator.Connect, Operator.Metro],
    managers: [Operator.Metro, Operator.TransportForStepford],
    signalZone: [SignalZone.A],
    platforms: [1, 2],
    dsGroups: [[1, 2]],
  },
  CLB: {
    name: "Carnalea Bridge",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signalZone: [SignalZone.H],
    platforms: [1],
  },
  CON: {
    name: "Connolly",
    operators: [Operator.Waterline],
    managers: [Operator.Waterline],
    signalZone: [SignalZone.F],
    platforms: [1, 2, 3],
    dsGroups: [[1, 2, 3]],
  },
  COX: {
    name: "Coxly",
    operators: [Operator.Connect, Operator.Metro],
    managers: [Operator.Metro, Operator.TransportForStepford],
    signalZone: [SignalZone.B],
    platforms: [1, 2, 3],
    dsGroups: [[1, 2, 3]],
  },
  CSP: {
    name: "Cambridge Street Parkway",
    operators: [Operator.Waterline],
    managers: [Operator.Waterline],
    signalZone: [SignalZone.F],
    platforms: [1, 2, 3],
    dsGroups: [[1, 2, 3]],
  },
  CXN: {
    name: "Coxly Newtown",
    operators: [Operator.Metro],
    managers: [Operator.Metro, Operator.TransportForStepford],
    signalZone: [SignalZone.B],
    platforms: [1, 2],
    dsGroups: [[1, 2]],
  },
  EBR: {
    name: "East Berrily",
    operators: [Operator.Metro],
    managers: [Operator.Metro, Operator.TransportForStepford],
    signalZone: [SignalZone.B],
    platforms: [1, 2],
    dsGroups: [[1, 2]],
  },
  EDG: {
    name: "Edgemead",
    operators: [Operator.Connect, Operator.Express],
    managers: [Operator.Connect],
    signalZone: [SignalZone.E],
    platforms: [1, 2, 3],
    dsGroups: [[1, 2, 3]],
  },
  EDQ: {
    name: "Eden Quay",
    operators: [Operator.Waterline],
    managers: [Operator.Waterline],
    signalZone: [SignalZone.F],
    platforms: [1, 2],
    dsGroups: [[1, 2]],
  },
  EFD: {
    name: "Esterfield",
    operators: [Operator.Waterline],
    managers: [Operator.Waterline],
    signalZone: [SignalZone.G],
    platforms: [1, 2, 3, "4B"], // 4A is a parked class 143
    dsGroups: [[1, 2, 3, "4B"]],
  },
  EMJ: {
    name: "Elsemere Junction",
    operators: [
      Operator.Connect,
      Operator.Metro,
      Operator.Airlink,
      Operator.Express,
    ],
    managers: [Operator.Airlink, Operator.TransportForStepford],
    signalZone: [SignalZone.B],
    platforms: [1, 2, 3, 4],
    dsGroups: [[1, 2, 3, 4]],
  },
  EMP: {
    name: "Elsemere Pond",
    operators: [Operator.Metro],
    managers: [Operator.Metro, Operator.TransportForStepford],
    signalZone: [SignalZone.B],
    platforms: [1, 2],
  },
  FAR: {
    name: "Farleigh",
    operators: [Operator.Waterline],
    managers: [Operator.Waterline],
    signalZone: [SignalZone.G],
    platforms: [1, 2],
    dsGroups: [[1, 2]],
  },
  FAY: {
    name: "Faymere",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signalZone: [SignalZone.E],
    platforms: [1, 2],
    dsGroups: [[1, 2]],
  },
  FNQ: {
    name: "Financial Quarter",
    operators: [Operator.Connect, Operator.Metro],
    managers: [Operator.Metro, Operator.TransportForStepford],
    signalZone: [SignalZone.A],
    platforms: [1, 2],
    dsGroups: [[1, 2]],
  },
  FRD: {
    name: "Faraday Road",
    operators: [Operator.Waterline],
    managers: [Operator.Waterline],
    signalZone: [SignalZone.F],
    platforms: [1, 2, 3],
    dsGroups: [[1, 2, 3]],
  },
  FWY: {
    name: "Four Ways",
    operators: [Operator.Metro],
    managers: [Operator.Metro, Operator.TransportForStepford],
    signalZone: [SignalZone.J],
    platforms: [1, 2],
    dsGroups: [[1, 2]],
  },
  GNS: {
    name: "Greenslade",
    operators: [Operator.Waterline],
    managers: [Operator.Waterline],
    signalZone: [SignalZone.F],
    platforms: [1, 2],
    dsGroups: [[1, 2]],
  },
  HHG: {
    name: "Hampton Hargate",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signalZone: [SignalZone.D],
    platforms: [1, 2],
  },
  HPK: {
    name: "Hemdon Park",
    operators: [Operator.Metro],
    managers: [Operator.Metro, Operator.TransportForStepford],
    signalZone: [SignalZone.A],
    platforms: [1, 2],
    dsGroups: [[1, 2]],
  },
  HTR: {
    name: "Houghton Rake",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signalZone: [SignalZone.A],
    platforms: [1, 2],
    dsGroups: [[1, 2]],
  },
  JST: {
    name: "James Street",
    operators: [Operator.Waterline],
    managers: [Operator.Waterline],
    signalZone: [SignalZone.G],
    platforms: [1, 2],
  },
  LSR: {
    name: "Leighton Stepford Road",
    operators: [Operator.Connect, Operator.Airlink, Operator.Express],
    managers: [Operator.Express],
    signalZone: [SignalZone.D],
    platforms: [1, 2, 3, 4, 5],
    dsGroups: [
      [1, 2, 3],
      [4, 5],
    ],
  },
  LTC: {
    name: "Leighton City",
    operators: [Operator.Connect, Operator.Express],
    managers: [Operator.NationalRail],
    signalZone: [SignalZone.D],
    platforms: [1, 2, 3, 4, 5, 6],
    dsGroups: [
      [1, 2, 3, 4],
      [5, 6],
    ],
  },
  LTW: {
    name: "Leighton West",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signalZone: [SignalZone.D],
    platforms: [1],
  },
  LYN: {
    name: "Llyn-by-the-Sea",
    operators: [Operator.Connect, Operator.Express],
    managers: [Operator.NationalRail],
    signalZone: [SignalZone.E],
    platforms: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    dsGroups: [
      [0, 1, 2, 3, 4, 5, 6],
      [7, 8, 9, 10, 11],
    ],
  },
  MGD: {
    name: "Morganstown Docks",
    operators: [Operator.Metro, Operator.Waterline],
    managers: [Operator.Waterline],
    signalZone: [SignalZone.F],
    platforms: [1, 2],
  },
  MGT: {
    name: "Morganstown",
    operators: [
      Operator.Connect,
      Operator.Metro,
      Operator.Waterline,
      Operator.Airlink,
      Operator.Express,
    ],
    managers: [Operator.NationalRail],
    signalZone: [SignalZone.D],
    platforms: [1, 2, 3, 4, 5, 6, 7],
    dsGroups: [[1, 2, 3, 4, 5, 6]],
  },
  MLC: {
    name: "Millcastle",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signalZone: [SignalZone.E],
    platforms: [1, 2],
    dsGroups: [[1, 2]],
  },
  MRC: {
    name: "Millcastle Racecourse",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signalZone: [SignalZone.E],
    platforms: [1, 2],
  },
  NHW: {
    name: "New Harrow",
    operators: [Operator.Metro],
    managers: [Operator.Metro, Operator.TransportForStepford],
    signalZone: [SignalZone.B],
    platforms: [1, 2],
  },
  NRH: {
    name: "Newry Harbour",
    operators: [Operator.Waterline, Operator.Express],
    managers: [Operator.Waterline],
    signalZone: [SignalZone.F],
    platforms: [1, 2],
    dsGroups: [[1, 2]],
  },
  NRY: {
    name: "Newry",
    operators: [Operator.Waterline, Operator.Express],
    managers: [Operator.Waterline],
    signalZone: [SignalZone.F],
    platforms: [1, 2, 3],
    dsGroups: [[1, 2, 3]],
  },
  NSE: {
    name: "Northshore",
    operators: [Operator.Connect, Operator.Express],
    managers: [Operator.Express],
    signalZone: [SignalZone.E],
    platforms: [1, 2, 3, 4],
    dsGroups: [[1, 2, 3, 4]],
  },
  PBN: {
    name: "Port Benton",
    operators: [Operator.Connect, Operator.Metro, Operator.Waterline],
    managers: [Operator.Connect],
    signalZone: [SignalZone.F],
    platforms: [1, 2, 3],
    dsGroups: [[1, 2, 3]],
  },
  RCP: {
    name: "Rocket Parade",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signalZone: [SignalZone.D],
    platforms: [1, 2],
  },
  RDV: {
    name: "Rosedale Village",
    operators: [Operator.Waterline],
    managers: [Operator.Waterline],
    signalZone: [SignalZone.G],
    platforms: [1, 2],
  },
  RLB: {
    name: "Rayleigh Bay",
    operators: [Operator.Connect, Operator.Express],
    managers: [Operator.Connect],
    signalZone: [SignalZone.H],
    platforms: [1, 2, 3],
    dsGroups: [[1, 2, 3]],
  },
  SAC: {
    name: "Stepford Airport Central",
    operators: [Operator.Connect, Operator.Airlink],
    managers: [Operator.Airlink, Operator.NationalRail],
    signalZone: [SignalZone.C],
    platforms: [0, 1, 2, 3, 4, 5, 6],
    dsGroups: [
      [3, 4, 5, 6],
      [0, 1, 2],
    ],
  },
  SAO: {
    name: "Airport Terminal 1",
    operators: [Operator.Airlink],
    managers: [Operator.Airlink],
    signalZone: [SignalZone.C],
    platforms: [1],
  },
  SAP: {
    name: "Stepford Airport Parkway",
    operators: [Operator.Connect, Operator.Airlink],
    managers: [Operator.Airlink],
    signalZone: [SignalZone.C],
    platforms: [1, 2, 3, 4, 5],
    dsGroups: [
      [1, 2],
      [3, 4, 5],
    ],
  },
  SAW: {
    name: "Stepford Airport West",
    operators: [Operator.Waterline],
    managers: [Operator.Waterline],
    signalZone: [SignalZone.C],
    platforms: [1, 2],
    dsGroups: [[1, 2]],
  },
  SAX: {
    name: "Airport Terminal 2",
    operators: [Operator.Connect, Operator.Waterline, Operator.Airlink],
    managers: [Operator.Airlink],
    signalZone: [SignalZone.C],
    platforms: [1, 2, 3, 4],
    dsGroups: [[1, 2, 3, 4]],
  },
  SAZ: {
    name: "Airport Terminal 3",
    operators: [Operator.Airlink],
    managers: [Operator.Airlink],
    signalZone: [SignalZone.C],
    platforms: [1, 2, 3],
    dsGroups: [[1, 2, 3]],
  },
  SCE: {
    name: "Stepford East",
    operators: [Operator.Connect, Operator.Metro, Operator.Airlink],
    managers: [Operator.TransportForStepford, Operator.NationalRail],
    signalZone: [SignalZone.A, SignalZone.J],
    platforms: [1, 2, 3, 4, 5, 6, 7, 8, "A", "B", "C", "D"],
    dsGroups: [
      [1, 2, 3, 4],
      ["A", "B", "C", "D"],
      [5, 6, 7, 8],
    ],
  },
  SCN: {
    name: "Stepford Central",
    operators: [
      Operator.Connect,
      Operator.Metro,
      Operator.Airlink,
      Operator.Express,
    ],
    managers: [Operator.TransportForStepford, Operator.NationalRail],
    signalZone: [SignalZone.A, SignalZone.J],
    platforms: [
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      "A",
      "B",
      "C",
      "D",
    ],
    dsGroups: [
      [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
      ["A", "B", "C", "D"],
      [12, 13, 14, 15],
      [10, 11],
    ],
  },
  SCV: {
    name: "Stepford Victoria",
    operators: [Operator.Connect, Operator.Metro],
    managers: [Operator.TransportForStepford, Operator.NationalRail],
    signalZone: [SignalZone.A],
    platforms: [1, 2, 3, 4, 5, 6],
    dsGroups: [[1, 2, 3, 4, 5, 6]],
  },
  SHB: {
    name: "St Helens Bridge",
    operators: [
      Operator.Connect,
      Operator.Metro,
      Operator.Airlink,
      Operator.Express,
    ],
    managers: [Operator.TransportForStepford, Operator.NationalRail],
    signalZone: [SignalZone.A],
    platforms: [1, 2, 3, 4, 5, 6, 7],
    dsGroups: [
      [1, 2, 3, 4, 5],
      [6, 7],
    ],
  },
  SHS: {
    name: "Stepford High Street",
    operators: [Operator.Metro],
    managers: [Operator.Metro, Operator.TransportForStepford],
    signalZone: [SignalZone.J],
    platforms: ["A", "B", "C", "D"],
    dsGroups: [["A", "B", "C", "D"]],
  },
  STL: {
    name: "Starryloch",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signalZone: [SignalZone.E],
    platforms: [1, 2],
  },
  UFC: {
    name: "Stepford UFC",
    operators: [Operator.Connect, Operator.Metro],
    managers: [Operator.Metro, Operator.TransportForStepford],
    signalZone: [SignalZone.A],
    platforms: [1, 2, 3, 4],
    dsGroups: [[1, 2, 3, 4]],
  },
  USL: {
    name: "Upper Staploe",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signalZone: [SignalZone.D],
    platforms: [1, 2],
  },
  WBN: {
    name: "West Benton",
    operators: [Operator.Waterline],
    managers: [Operator.Waterline],
    signalZone: [SignalZone.F],
    platforms: [1, 2],
    dsGroups: [[1, 2]],
  },
  WFD: {
    name: "Willowfield",
    operators: [Operator.Connect, Operator.Metro],
    managers: [Operator.Metro, Operator.TransportForStepford],
    signalZone: [SignalZone.A],
    platforms: [1, 2, 3],
    dsGroups: [[1, 2, 3]],
  },
  WFL: {
    name: "Whitefield Lido",
    operators: [Operator.Metro],
    managers: [Operator.Metro, Operator.TransportForStepford],
    signalZone: [SignalZone.A],
    platforms: [1, 2],
    dsGroups: [[1, 2]],
  },
  WHF: {
    name: "Whitefield",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signalZone: [SignalZone.A],
    platforms: [1, 2, 3],
    dsGroups: [[1, 2, 3]],
  },
  WHL: {
    name: "Woodhead Lane",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signalZone: [SignalZone.A],
    platforms: [1, 2],
    dsGroups: [[1, 2]],
  },
  WNG: {
    name: "Whitney Green",
    operators: [Operator.Waterline],
    managers: [Operator.Waterline],
    signalZone: [SignalZone.F],
    platforms: [1, 2],
  },
  WST: {
    name: "Westercoast",
    operators: [Operator.Connect, Operator.Express],
    managers: [Operator.Connect],
    signalZone: [SignalZone.E],
    platforms: [1, 2],
  },
  WTN: {
    name: "Water Newton",
    operators: [Operator.Connect, Operator.Airlink],
    managers: [Operator.Connect],
    signalZone: [SignalZone.D],
    platforms: [1, 2, 3, 4],
    dsGroups: [[1, 2, 3, 4]],
  },
  WYV: {
    name: "Westwyvern",
    operators: [Operator.Connect, Operator.Express],
    managers: [Operator.Express],
    signalZone: [SignalZone.E],
    platforms: [1, 2, 3, 4],
    dsGroups: [[1, 2, 3, 4]],
  },
};

export type SignalZoneInfo = {
  name: string;
  location: string;
  locationStation: string;
};

export const signal_zones: Record<SignalZone, SignalZoneInfo> = {
  [SignalZone.A]: {
    name: "Stepford Zone/Willowfield Line/Whitefield Line",
    location: "Stepford ROC",
    locationStation: "Stepford Central",
  },
  [SignalZone.B]: {
    name: "St Helens Bridge to Coxly/Beaulieu Park/Barton",
    location: "Beaulieu Park Signal Box",
    locationStation: "Beaulieu Park",
  },
  [SignalZone.C]: {
    name: "Stepford Airport Zone/Benton Bridge",
    location: "Airport ROC",
    locationStation: "Stepford Airport Central",
  },
  [SignalZone.D]: {
    name: "Morganstown to Leighton West/Airport Parkway Depot",
    location: "Stepford ROC",
    locationStation: "Stepford Central",
  },
  [SignalZone.E]: {
    name: "Edgemead to Llyn-by-the-Sea",
    location: "Llyn-by-the-Sea ROC",
    locationStation: "Llyn-by-the-Sea",
  },
  [SignalZone.F]: {
    name: "Benton Zone/Conolly Line/Greenslade Line/Newry Line",
    location: "Benton Signal Box",
    locationStation: "Benton",
  },
  [SignalZone.G]: {
    name: "Farleigh Depot to Esterfield",
    location: "Stepford ROC",
    locationStation: "Stepford Central",
  },
  [SignalZone.H]: {
    name: "Aslockby to Rayleigh Bay",
    location: "Rayleigh Bay Signal Box",
    locationStation: "Rayleigh Bay",
  },
  [SignalZone.J]: {
    name: "Metro Core Section (Stepford Cetral to Stepford High Street)",
    location: "High Street Signalling Centre",
    locationStation: "Stepford High Street",
  },
};
