export enum Operator {
  Airlink,
  Connect,
  Express,
  Waterline,
  Metro,
  NationalRail,
  TransportForStepford,
}

export enum SignalZone {
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  J,
}

type RouteInfo = {
  operator: Operator;
  inboundDestination: string;
  inboundDepots?: string[];
  outboundDestination?: string;
  outboundDepots?: string[];
  altName?: string;
};

export const routes: Record<string, RouteInfo> = {
  R001: {
    operator: Operator.Connect,
    inboundDestination: "Stepford Central",
    inboundDepots: [
      "Farleigh Depot (Road 11)",
      "Benton Depot",
      "Stepford Depot",
    ],
    outboundDestination: "Airport Central",
    outboundDepots: ["Coxly Station Siding", "Coxly Bypass Siding"],
  },
  R002: {
    operator: Operator.Metro,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Benton Depot", "Stepford Depot"],
    outboundDestination: "Port Benton",
    outboundDepots: ["Coxly Station Siding", "Coxly Bypass Siding"],
  },
  R003: {
    operator: Operator.Connect,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Benton Depot", "Stepford Depot"],
    outboundDestination: "Leighton City",
    outboundDepots: [
      "Coxly Station Siding",
      "Coxly Bypass Siding",
      "Hampton Hargate Siding",
      "Leighton Depot",
    ],
  },
  R004: {
    operator: Operator.Connect,
    inboundDestination: "St Helens Bridge",
    inboundDepots: ["Faymere Green NB Depot", "Benton Depot"],
    outboundDestination: "Edgemead",
    outboundDepots: [
      "Coxly Station Siding",
      "Coxly Bypass Siding",
      "Hampton Hargate Siding",
      "Leighton Depot",
    ],
  },
  R005: {
    operator: Operator.Connect,
    inboundDestination: "Stepford Victoria",
    inboundDepots: [
      "Farleigh Depot (Road 11)",
      "Benton Depot",
      "Stepford Depot",
      "Beechley Sidings",
    ],
    outboundDestination: "Airport Central",
    outboundDepots: [
      "Beechley Sidings",
      "Coxly Station Siding",
      "Coxly Bypass Siding",
    ],
  },
  R006: {
    operator: Operator.Metro,
    inboundDestination: "Stepford Victoria",
    inboundDepots: ["Benton Depot", "Stepford Depot", "Beechley Sidings"],
    outboundDestination: "Port Benton",
    outboundDepots: [
      "Beechley Sidings",
      "Coxly Station Siding",
      "Coxly Bypass Siding",
    ],
  },
  R007: {
    operator: Operator.Connect,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Berrily Depot (WB)", "Stepford Depot"],
    outboundDestination: "Morganstown",
    outboundDepots: ["Berrily Depot (EB)"],
  },
  R008: {
    operator: Operator.Metro,
    inboundDestination: "Stepford Victoria",
    inboundDepots: ["Berrily Depot (WB)", "Stepford Depot", "Beechley Sidings"],
    outboundDestination: "Berrily",
    outboundDepots: ["Beechley Sidings"],
  },
  R009: {
    operator: Operator.Metro,
    inboundDestination: "Stepford Victoria",
    inboundDepots: [
      "Faymere Green NB Depot",
      "Benton Depot",
      "Stepford Depot",
      "Beechley Sidings",
    ],
    outboundDestination: "Edgemead",
    outboundDepots: [
      "Beechley Sidings",
      "Coxly Station Siding",
      "Coxly Bypass Siding",
      "Hampton Hargate Siding",
      "Leighton Depot",
    ],
  },
  R010: {
    operator: Operator.Waterline,
    inboundDestination: "Newry",
    inboundDepots: ["Faraday Road Depot", "Newry Siding"],
    outboundDestination: "Greenslade",
    outboundDepots: ["Benton Siding", "Whitney Green Depot"],
  },
  R011: {
    operator: Operator.Waterline,
    inboundDestination: "Newry",
    inboundDepots: ["Faraday Road Depot", "Newry Siding"],
    outboundDestination: "Connolly",
    outboundDepots: ["Benton Siding"],
  },
  R012: {
    operator: Operator.Waterline,
    inboundDestination: "Newry Harbour",
    inboundDepots: ["Faraday Road Depot", "Newry Siding"],
    outboundDestination: "Connolly",
    outboundDepots: ["Benton Siding"],
  },
  R013: {
    operator: Operator.Waterline,
    inboundDestination: "Benton",
    outboundDestination: "Greenslade",
    outboundDepots: ["Benton Siding", "Whitney Green Depot"],
  },
  R014: {
    operator: Operator.Waterline,
    inboundDestination: "Newry",
    inboundDepots: [
      "Esterfield Mainline Depot",
      "Faraday Road Depot",
      "Newry Siding",
    ],
    outboundDestination: "Esterfield",
    outboundDepots: [
      "Benton Siding",
      "Farleigh Depot (Road 2)",
      "Esterfield Station Depot",
    ],
  },
  R015: {
    operator: Operator.Waterline,
    inboundDestination: "Benton",
    inboundDepots: ["Morganstown Siding"],
    outboundDestination: "Morganstown",
    outboundDepots: ["Benton Siding"],
    altName: "Morganstown Shuttle",
  },
  R016: {
    operator: Operator.Waterline,
    inboundDestination: "Benton",
    inboundDepots: ["Esterfield Mainline Depot"],
    outboundDestination: "Esterfield",
    outboundDepots: [
      "Benton Siding",
      "Farleigh Depot (Road 2)",
      "Esterfield Station Depot",
    ],
  },
  R017: {
    operator: Operator.Waterline,
    inboundDestination: "Newry",
    inboundDepots: ["Faraday Road Depot", "Newry Siding"],
    outboundDestination: "Terminal 2",
    outboundDepots: ["Benton Siding", "Farleigh Depot (Road 17)"],
  },
  R018: {
    operator: Operator.Waterline,
    inboundDestination: "Newry Harbour",
    inboundDepots: ["Faraday Road Depot", "Newry Siding"],
    outboundDestination: "Farleigh",
    outboundDepots: ["Benton Siding", "Farleigh Depot (Road 2)"],
  },
  R019: {
    operator: Operator.Waterline,
    inboundDestination: "Benton",
    outboundDestination: "Connolly",
    outboundDepots: ["Benton Siding"],
  },
  R020: {
    operator: Operator.Connect,
    inboundDestination: "Stepford Central",
    inboundDepots: [
      "Whitefield Siding",
      "Woodhead Lane SB Depot",
      "Stepford Depot",
    ],
    outboundDestination: "Whitefield",
    outboundDepots: ["Woodhead Lane NB Depot"],
  },
  R021: {
    operator: Operator.Metro,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Woodhead Lane SB Depot", "Stepford Depot"],
    outboundDestination: "Stepford United Football Club",
  },
  R022: {
    operator: Operator.Connect,
    inboundDestination: "Beechley",
    inboundDepots: [
      "Whitefield Siding",
      "Woodhead Lane SB Depot",
      "Stepford Depot",
    ],
    outboundDestination: "Whitefield",
    outboundDepots: ["Beechley Sidings", "Woodhead Lane NB Depot"],
  },
  R023: {
    operator: Operator.Metro,
    inboundDestination: "Stepford Victoria",
    inboundDepots: [
      "Woodhead Lane SB Depot",
      "Stepford Depot",
      "Beechley Sidings",
    ],
    outboundDestination: "Stepford United Football Club",
    outboundDepots: ["Beechley Sidings"],
  },
  R024: {
    operator: Operator.Connect,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Faymere Green NB Depot", "Benton Depot", "Stepford Depot"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: [
      "Coxly Station Siding",
      "Coxly Bypass Siding",
      "Hampton Hargate Siding",
      "Leighton Depot",
      "Faymere Green SB Depot",
      "Northshore Depot",
    ],
  },
  R025: {
    operator: Operator.Connect,
    inboundDestination: "St Helens Bridge",
    inboundDepots: ["Faymere Green NB Depot", "Benton Depot"],
    outboundDestination: "Westwyern",
    outboundDepots: [
      "Coxly Station Siding",
      "Coxly Bypass Siding",
      "Hampton Hargate Siding",
      "Leighton Depot",
      "Faymere Green SB Depot",
    ],
  },
  R026: {
    operator: Operator.Connect,
    inboundDestination: "Stepford Victoria",
    inboundDepots: [
      "Faymere Green NB Depot",
      "Benton Depot",
      "Stepford Depot",
      "Beechley Sidings",
    ],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: [
      "Beechley Sidings",
      "Coxly Station Siding",
      "Coxly Bypass Siding",
      "Hampton Hargate Siding",
      "Leighton Depot",
      "Faymere Green SB Depot",
      "Northshore Depot",
    ],
  },
  R027: {
    operator: Operator.Metro,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Berrily Depot (WB)", "Stepford Depot"],
    outboundDestination: "Berrily",
  },
  R028: {
    operator: Operator.Metro,
    inboundDestination: "Stepford Victoria",
    inboundDepots: ["Willowfield Depot", "Beechley Sidings"],
    outboundDestination: "Willowfield",
    outboundDepots: ["Willowfield Depot"],
  },
  R029: {
    operator: Operator.Metro,
    inboundDestination: "Stepford Victoria",
    inboundDepots: ["Beechley Sidings"],
    outboundDestination: "Beechley",
  },
  R030: {
    operator: Operator.Metro,
    inboundDestination: "Willowfield",
    inboundDepots: [
      "Berrily Depot (WB)",
      "Stepford Depot",
      "Willowfield Depot",
    ],
    outboundDestination: "Berrily",
    outboundDepots: ["Willowfield Depot", "Beechley Sidings"],
  },
  R031: {
    operator: Operator.Metro,
    inboundDestination: "Willowfield",
    inboundDepots: ["Woodhead Lane SB Depot"],
    outboundDestination: "Stepford United Football Club",
    outboundDepots: ["Willowfield Depot", "Beechley Sidings"],
  },
  R032: {
    operator: Operator.Connect,
    inboundDestination: "Willowfield",
    inboundDepots: ["Benton Depot", "Stepford Depot", "Willowfield Depot"],
    outboundDestination: "Port Benton",
    outboundDepots: [
      "Willowfield Depot",
      "Beechley Sidings",
      "Coxly Station Siding",
      "Coxly Bypass Siding",
    ],
  },
  R033: {
    operator: Operator.Connect,
    inboundDestination: "Beechley",
    inboundDepots: [
      "Farleigh Depot (Road 11)",
      "Benton Depot",
      "Stepford Depot",
    ],
    outboundDestination: "Airport Central",
    outboundDepots: [
      "Beechley Sidings",
      "Coxly Station Siding",
      "Coxly Bypass Siding",
    ],
  },
  R034: {
    operator: Operator.Metro,
    inboundDestination: "Beechley",
    inboundDepots: ["Berrily Depot (WB)", "Stepford Depot"],
    outboundDestination: "Morganstown",
    outboundDepots: ["Beechley Sidings", "Berrily Depot (EB)"],
  },
  R035: {
    operator: Operator.Connect,
    inboundDestination: "Willowfield",
    inboundDepots: [
      "Faymere Green NB Depot",
      "Benton Depot",
      "Stepford Depot",
      "Willowfield Depot",
    ],
    outboundDestination: "Westwyvern",
    outboundDepots: [
      "Willowfield Depot",
      "Beechley Sidings",
      "Coxly Station Siding",
      "Coxly Bypass Siding",
      "Hampton Hargate Siding",
      "Leighton Depot",
      "Faymere Green SB Depot",
    ],
  },
  R036: {
    operator: Operator.Connect,
    inboundDestination: "Willowfield",
    inboundDepots: [
      "Faymere Green NB Depot",
      "Benton Depot",
      "Stepford Depot",
      "Willowfield Depot",
    ],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: [
      "Willowfield Depot",
      "Beechley Sidings",
      "Coxly Station Siding",
      "Coxly Bypass Siding",
      "Hampton Hargate Siding",
      "Leighton Depot",
      "Faymere Green SB Depot",
      "Northshore Depot",
    ],
  },
  R037: {
    operator: Operator.Connect,
    inboundDestination: "Leighton City",
    inboundDepots: ["Faymere Green NB Depot"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: ["Faymere Green SB Depot", "Northshore Depot"],
  },
  R038: {
    operator: Operator.Connect,
    inboundDestination: "Leighton City",
    inboundDepots: ["Faymere Green NB Depot"],
    outboundDestination: "Westwyvern",
    outboundDepots: ["Faymere Green SB Depot"],
  },
  R039: {
    operator: Operator.Connect,
    inboundDestination: "Benton",
    outboundDestination: "Leighton City",
    outboundDepots: [
      "Coxly Bypass Siding",
      "Hampton Hargate Siding",
      "Leighton Depot",
    ],
  },
  R040: {
    operator: Operator.Connect,
    inboundDestination: "Edgemead",
    inboundDepots: ["Faymere Green NB Depot"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: ["Faymere Green SB Depot", "Northshore Depot"],
  },
  R041: {
    operator: Operator.Connect,
    inboundDestination: "Leighton West",
    inboundDepots: ["Faymere Green NB Depot"],
    outboundDestination: "Edgemead",
  },
  R042: {
    operator: Operator.Connect,
    inboundDestination: "Leighton West",
    inboundDepots: ["Faymere Green NB Depot"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: ["Faymere Green SB Depot", "Northshore Depot"],
  },
  R043: {
    operator: Operator.Connect,
    inboundDestination: "Leighton West",
    inboundDepots: ["Leighton Depot"],
    outboundDestination: "Leighton City",
  },
  R044: {
    operator: Operator.Connect,
    inboundDestination: "Benton",
    outboundDestination: "Leighton West",
    outboundDepots: [
      "Coxly Bypass Siding",
      "Hampton Hargate Siding",
      "Leighton Depot",
    ],
  },
  R045: {
    operator: Operator.Connect,
    inboundDestination: "Stepford Victoria",
    inboundDepots: ["Benton Depot", "Stepford Depot", "Beechley Sidings"],
    outboundDestination: "Leighton City",
    outboundDepots: [
      "Beechley Sidings",
      "Coxly Station Siding",
      "Coxly Bypass Siding",
      "Hampton Hargate Siding",
      "Leighton Depot",
    ],
  },
  R046: {
    operator: Operator.Connect,
    inboundDestination: "Stepford Victoria",
    inboundDepots: [
      "Farleigh Depot (Road 11)",
      "Benton Depot",
      "Stepford Depot",
      "Beechley Sidings",
    ],
    outboundDestination: "Terminal 2",
    outboundDepots: [
      "Beechley Sidings",
      "Coxly Station Siding",
      "Coxly Bypass Siding",
      "Farleigh Depot (Road 17)",
    ],
  },
  R047: {
    operator: Operator.Metro,
    inboundDestination: "St Helens Bridge",
    inboundDepots: ["Benton Depot"],
    outboundDestination: "Port Benton",
    outboundDepots: ["Coxly Station Siding", "Coxly Bypass Siding"],
  },
  R048: {
    operator: Operator.Connect,
    inboundDestination: "St Helens Bridge",
    inboundDepots: ["	Farleigh Depot (Road 11)", "Benton Depot"],
    outboundDestination: "Terminal 2",
    outboundDepots: [
      "Coxly Station Siding",
      "Coxly Bypass Siding",
      "Farleigh Depot (Road 17)",
    ],
  },
  R049: {
    operator: Operator.Connect,
    inboundDestination: "Rayleigh Bay",
    inboundDepots: ["Faymere Green NB Depot"],
    outboundDestination: "Edgemead",
  },
  R050: {
    operator: Operator.Connect,
    inboundDestination: "Rayleigh Bay",
    inboundDepots: ["Faymere Green NB Depot"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: ["Faymere Green SB Depot", "Northshore Depot"],
  },
  R051: {
    operator: Operator.Airlink,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Farleigh Depot (Road 11)", "Stepford Depot"],
    outboundDestination: "Airport Central",
    outboundDepots: ["Airport Parkway Siding"],
  },
  R052: {
    operator: Operator.Airlink,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Farleigh Depot (Road 11)", "Stepford Depot"],
    outboundDestination: "Terminal 2",
    outboundDepots: ["Airport Parkway Siding", "Airport Parkway Siding"],
  },
  R053: {
    operator: Operator.Airlink,
    inboundDestination: "Stepford Central",
    inboundDepots: [
      "Farleigh Depot (Road 11)",
      "Airport Parkway Depot",
      "Stepford Depot",
    ],
    outboundDestination: "Terminal 2",
    outboundDepots: ["Airport Parkway Siding", "Farleigh Depot (Road 17)"],
  },
  R054: {
    operator: Operator.Airlink,
    inboundDestination: "Stepford Central",
    inboundDepots: [
      "Farleigh Depot (Road 11)",
      "Airport Parkway Depot",
      "Stepford Depot",
    ],
    outboundDestination: "Airport Central",
    outboundDepots: ["Airport Parkway Siding"],
  },
  R055: {
    operator: Operator.Airlink,
    inboundDestination: "Stepford Central",
    inboundDepots: [
      "Farleigh Depot (Road 11)",
      "Airport Parkway Depot",
      "Stepford Depot",
    ],
    outboundDestination: "Terminal 3",
    outboundDepots: ["Airport Parkway Siding", "Farleigh Depot (Road 17)"],
  },
  R056: {
    operator: Operator.Airlink,
    inboundDestination: "Airport Central",
    inboundDepots: ["Airport Parkway Siding"],
    outboundDestination: "Leighton Stepford Road",
    outboundDepots: ["Farleigh Depot (Road 11)", "Leighton Depot"],
  },
  R057: {
    operator: Operator.Airlink,
    inboundDestination: "Terminal 3",
    inboundDepots: ["Farleigh Depot (Road 17)"],
    outboundDestination: "Leighton Stepford Road",
    outboundDepots: [
      "Farleigh Depot (Road 11)",
      "Airport Parkway Depot",
      "Leighton Depot",
    ],
  },
  R058: {
    operator: Operator.Airlink,
    inboundDestination: "Stepford Central",
    inboundDepots: [
      "Farleigh Depot (Road 17)",
      "Farleigh Depot (Road 11)",
      "Stepford Depot",
    ],
    outboundDestination: "Terminal 3",
    outboundDepots: ["Airport Parkway Siding"],
  },
  R059: {
    operator: Operator.Airlink,
    inboundDestination: "Stepford Central",
    inboundDepots: [
      "Farleigh Depot (Road 11)",
      "Airport Parkway Depot",
      "Stepford Depot",
    ],
    outboundDestination: "Terminal 2",
    outboundDepots: ["Airport Parkway Siding", "Farleigh Depot (Road 17)"],
  },
  R060: {
    operator: Operator.Airlink,
    inboundDestination: "Airport Parkway",
    inboundDepots: ["Farleigh Depot (Road 11)"],
    outboundDestination: "Terminal 2",
    outboundDepots: ["Airport Parkway Siding", "Farleigh Depot (Road 17)"],
    altName: "Terminals Shuttle",
  },
  R061: {
    operator: Operator.Airlink,
    inboundDestination: "Airport Central",
    inboundDepots: ["Faymere Green NB Depot", "Airport Parkway Siding"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: [
      "Farleigh Depot (Road 11)",
      "Leighton Depot",
      "Faymere Green SB Depot",
      "Northshore Depot",
    ],
  },
  R062: {
    operator: Operator.Airlink,
    inboundDestination: "Terminal 3",
    inboundDepots: ["Faymere Green NB Depot", "Airport Parkway Siding"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: [
      "Farleigh Depot (Road 17)",
      "Farleigh Depot (Road 11)",
      "Leighton Depot",
      "Faymere Green SB Depot",
      "Northshore Depot",
    ],
  },
  R075: {
    operator: Operator.Express,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Benton Depot", "Stepford Depot"],
    outboundDestination: "Benton",
    outboundDepots: ["Coxly Bypass Siding"],
    altName: "Benton Express (fast)",
  },
  R076: {
    operator: Operator.Express,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Benton Depot", "Stepford Depot"],
    outboundDestination: "Leighton City",
    outboundDepots: ["Coxly Bypass Siding", "Leighton Depot"],
    altName: "Leighton Express",
  },
  R077: {
    operator: Operator.Express,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Faymere Green NB Depot", "Benton Depot", "Stepford Depot"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: [
      "Coxly Bypass Siding",
      "Leighton Depot",
      "Faymere Green SB Depot",
      "Northshore Depot",
    ],
    altName: "Llyn via Benton",
  },
  R078: {
    operator: Operator.Express,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Faymere Green NB Depot", "Benton Depot", "Stepford Depot"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: [
      "Coxly Bypass Siding",
      "Leighton Depot",
      "Faymere Green SB Depot",
      "Northshore Depot",
    ],
    altName: "Llyn via Benton (fast)",
  },
  R079: {
    operator: Operator.Express,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Benton Depot", "Stepford Depot"],
    outboundDestination: "Benton",
    outboundDepots: ["Coxly Bypass Siding"],
    altName: "Benton Express",
  },
  R080: {
    operator: Operator.Express,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Faymere Green NB Depot", "Stepford Depot"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: [
      "Leighton Depot",
      "Faymere Green SB Depot",
      "Northshore Depot",
    ],
    altName: "Llyn via Morganstown (fast)",
  },
  R081: {
    operator: Operator.Express,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Faymere Green NB Depot", "Stepford Depot"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: ["Leighton Depot", "Northshore Depot"],
    altName: "Llyn (super fast)",
  },
  R082: {
    operator: Operator.Express,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Faymere Green NB Depot", "Stepford Depot"],
    outboundDestination: "Westwyvern",
    outboundDepots: ["Leighton Depot", "Faymere Green SB Depot"],
    altName: "Westwyvern Express",
  },
  R083: {
    operator: Operator.Express,
    inboundDestination: "Newry",
    inboundDepots: ["Faymere Green NB Depot", "Newry Siding"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: [
      "Leighton Depot",
      "Faymere Green SB Depot",
      "Northshore Depot",
    ],
    altName: "Newry to Llyn",
  },
  R084: {
    operator: Operator.Express,
    inboundDestination: "Newry Harbour",
    inboundDepots: ["Faymere Green NB Depot", "Newry Siding"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: [
      "Leighton Depot",
      "Faymere Green SB Depot",
      "Northshore Depot",
    ],
    altName: "Newry Harbour to Llyn",
  },
  R085: {
    operator: Operator.Express,
    inboundDestination: "Benton",
    inboundDepots: ["Faymere Green NB Depot"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: [
      "Leighton Depot",
      "Faymere Green SB Depot",
      "Northshore Depot",
    ],
    altName: "Benton to Llyn",
  },
  R086: {
    operator: Operator.Express,
    inboundDestination: "Newry",
    inboundDepots: ["Faraday Road Depot", "Newry Siding"],
    outboundDestination: "Leighton City",
    outboundDepots: ["Leighton Depot"],
    altName: "Newry to Leighton City",
  },
  R087: {
    operator: Operator.Express,
    inboundDestination: "Llyn-by-the-Sea",
    inboundDepots: ["Faymere Green SB Depot", "Northshore Depot"],
    outboundDestination: "Rayleigh Bay",
    outboundDepots: ["Faymere Green NB Depot"],
    altName: "Rayleigh Bay Express",
  },
  R088: {
    operator: Operator.Express,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Faymere Green NB Depot", "Benton Depot", "Stepford Depot"],
    outboundDestination: "Llyn-by-the-Sea",
    outboundDepots: [
      "Coxly Bypass Siding",
      "Leighton Depot",
      "Faymere Green SB Depot",
      "Northshore Depot",
    ],
    altName: "Llyn via Benton (Westercoast Express)",
  },
  R100: {
    operator: Operator.Connect,
    inboundDestination: "Rayleigh Bay",
    inboundDepots: ["Leighton Depot"],
    outboundDestination: "Leighton West",
    outboundDepots: ["Faymere Green NB Depot"],
  },
  R101: {
    operator: Operator.Connect,
    inboundDestination: "Rayleigh Bay",
    inboundDepots: ["Leighton Depot"],
    outboundDestination: "Leighton City",
  },
  R102: {
    operator: Operator.Connect,
    inboundDestination: "Rayleigh Bay",
    inboundDepots: ["Faymere Green NB Depot"],
    outboundDestination: "Westwyvern",
    outboundDepots: ["Faymere Green SB Depot"],
  },
  R103: {
    operator: Operator.Connect,
    inboundDestination: "Willowfield",
    inboundDepots: [
      "Whitefield Siding",
      "Woodhead Lane SB Depot",
      "Stepford Depot",
      "Willowfield Depot",
    ],
    outboundDestination: "Whitefield",
    outboundDepots: [
      "Willowfield Depot",
      "Beechley Sidings",
      "Woodhead Lane NB Depot",
    ],
  },
  R120: {
    operator: Operator.Waterline,
    inboundDestination: "Newry Harbour",
    inboundDepots: ["Morganstown Siding", "Faraday Road Depot", "Newry Siding"],
    outboundDestination: "Morganstown",
    outboundDepots: ["Benton Siding"],
  },
  R130: {
    operator: Operator.Metro,
    inboundDestination: "Stepford Central",
    inboundDepots: ["Berrily Depot (WB)", "Stepford Depot"],
    outboundDestination: "Morganstown",
    outboundDepots: ["Berrily Depot (EB)"],
  },
  R131: {
    operator: Operator.Metro,
    inboundDestination: "St Helens Bridge",
    inboundDepots: ["Berrily Depot (WB)"],
    outboundDestination: "Morganstown",
    outboundDepots: ["Berrily Depot (EB)"],
  },
  R132: {
    operator: Operator.Metro,
    inboundDestination: "Barton",
    outboundDestination: "Stepford Central",
    outboundDepots: ["Berrily Depot (WB)", "Stepford Depot"],
    altName: "Stepford Central <> Barton (Clockwise)",
  },
  R133: {
    operator: Operator.Metro,
    inboundDestination: "Barton",
    inboundDepots: ["Willowfield Depot", "Beechley Sidings"],
    outboundDestination: "Willowfield",
    outboundDepots: [
      "Willowfield Depot",
      "Stepford Depot",
      "Berrily Depot (WB)",
    ],
    altName: "Willowfield <> Barton (Clockwise)",
  },
  R134: {
    operator: Operator.Metro,
    inboundDestination: "Barton",
    outboundDestination: "St Helens Bridge",
    outboundDepots: ["Berrily Depot (WB)"],
    altName: "St Helens Bridge <> Barton (Clockwise)",
  },
  R135: {
    operator: Operator.Metro,
    inboundDestination: "Barton",
    inboundDepots: ["Beechley Sidings"],
    outboundDestination: "Beechley",
    outboundDepots: ["Stepford Depot"],
    altName: "Beechley <> Barton (Anti-clockwise)",
  },
  R136: {
    operator: Operator.Metro,
    inboundDestination: "Barton",
    inboundDepots: ["Beechley Sidings"],
    outboundDestination: "Stepford Victoria",
    outboundDepots: ["Stepford Depot", "Beechley Sidings"],
    altName: "Stepford Victoria <> Barton (Anti-clockwise)",
  },
  R137: {
    operator: Operator.Metro,
    inboundDestination: "Stepford Victoria",
    inboundDepots: [
      "Morganstown Siding",
      "Benton Depot",
      "Stepford Depot",
      "Beechley Sidings",
    ],
    outboundDestination: "Morganstown",
    outboundDepots: [
      "Beechley Sidings",
      "Coxly Station Siding",
      "Coxly Bypass Siding",
    ],
    altName: "Stepford Victoria <> M'Town via Benton",
  },
};

type StationInfo = {
  name: string;
  operators: Operator[];
  managers: Operator[];
  signalZone?: SignalZone;
  platforms: (string | number)[];
  dsGroups?: (string | number)[][];
};

export const stations: Record<string, StationInfo> = {
  AGP: {
    name: "Angel Pass",
    operators: [Operator.Connect, Operator.Metro],
    managers: [Operator.Metro, Operator.TransportForStepford],
    signalZone: SignalZone.B,
    platforms: [1, 2, 3],
    dsGroups: [[1, 2, 3]],
  },
  ALB: {
    name: "Aslockby",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signalZone: SignalZone.H,
    platforms: [1, 2],
  },
  APK: {
    name: "Ashlan Park",
    operators: [Operator.Waterline],
    managers: [Operator.Waterline],
    signalZone: SignalZone.F,
    platforms: [1, 2],
  },
  BNB: {
    name: "Benton Bridge",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signalZone: SignalZone.C,
    platforms: [1, 2, 3, 4],
    dsGroups: [[1, 2, 3, 4]],
  },
  BAR: {
    name: "Barton",
    operators: [Operator.Metro],
    managers: [Operator.Metro, Operator.TransportForStepford],
    signalZone: SignalZone.B,
    platforms: [1, 2],
    dsGroups: [[1, 2]],
  },
  BCY: {
    name: "Beechley",
    operators: [Operator.Connect, Operator.Metro],
    managers: [Operator.Metro, Operator.TransportForStepford],
    signalZone: SignalZone.A,
    platforms: [1, 2, 3, 4],
    dsGroups: [[1, 2, 3, 4]],
  },
  BEN: {
    name: "Benton",
    operators: [
      Operator.Connect,
      Operator.Metro,
      Operator.Waterline,
      Operator.Express,
    ],
    managers: [Operator.NationalRail],
    signalZone: SignalZone.F,
    platforms: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
    dsGroups: [
      [1, 2, 3],
      [4, 5, 6, 7],
      [8, 9, 10, 11, 12, 13],
    ],
  },
  BOD: {
    name: "Bodin",
    operators: [Operator.Connect, Operator.Metro],
    managers: [Operator.Metro, Operator.TransportForStepford],
    signalZone: SignalZone.B,
    platforms: [1, 2, 3],
    dsGroups: [[1, 2, 3]],
  },
  BPK: {
    name: "Beaulieu Park",
    operators: [Operator.Metro],
    managers: [Operator.Metro, Operator.TransportForStepford],
    signalZone: SignalZone.B,
    platforms: [1, 2],
    dsGroups: [[1, 2]],
  },
  BRY: {
    name: "Berrily",
    operators: [Operator.Connect, Operator.Metro, Operator.Airlink],
    managers: [Operator.Metro, Operator.TransportForStepford],
    signalZone: SignalZone.B,
    platforms: [1, 2, 3, 4],
    dsGroups: [[1, 2, 3, 4]],
  },
  CHP: {
    name: "City Hospital",
    operators: [Operator.Connect, Operator.Metro],
    managers: [Operator.Metro, Operator.TransportForStepford],
    signalZone: SignalZone.A,
    platforms: [1, 2],
    dsGroups: [[1, 2]],
  },
  CLB: {
    name: "Carnalea Bridge",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signalZone: SignalZone.H,
    platforms: [1],
  },
  CON: {
    name: "Connolly",
    operators: [Operator.Waterline],
    managers: [Operator.Waterline],
    signalZone: SignalZone.F,
    platforms: [1, 2, 3],
    dsGroups: [[1, 2, 3]],
  },
  COX: {
    name: "Coxly",
    operators: [Operator.Connect, Operator.Metro],
    managers: [Operator.Metro, Operator.TransportForStepford],
    signalZone: SignalZone.B,
    platforms: [1, 2, 3],
    dsGroups: [[1, 2, 3]],
  },
  CSP: {
    name: "Cambridge Street Parkway",
    operators: [Operator.Waterline],
    managers: [Operator.Waterline],
    signalZone: SignalZone.F,
    platforms: [1, 2, 3],
    dsGroups: [[1, 2, 3]],
  },
  CXN: {
    name: "Coxly Newtown",
    operators: [Operator.Metro],
    managers: [Operator.Metro, Operator.TransportForStepford],
    signalZone: SignalZone.B,
    platforms: [1, 2],
    dsGroups: [[1, 2]],
  },
};
